# Generated by Django 3.2.4 on 2021-07-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='afprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='ogprice',
            field=models.FloatField(max_length=100),
        ),
    ]
