# Generated by Django 3.2.4 on 2021-07-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210705_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mods', models.CharField(max_length=1)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sales')),
            ],
        ),
    ]
