# Generated by Django 3.2.4 on 2021-07-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='date',
            field=models.DateField(verbose_name='Adding date'),
        ),
    ]
