# Generated by Django 3.2.4 on 2021-07-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_mod_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mod',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='mod',
            name='mods',
            field=models.CharField(choices=[('U', 'Unofficial_patch'), ('G', 'Graphical_art'), ('A', 'Add_on')], max_length=1),
        ),
        migrations.AddField(
            model_name='sales',
            name='genres',
            field=models.ManyToManyField(to='main_app.Genres'),
        ),
    ]
